### ISSUE TITLE
Crash ingame

### ISSUE THREAD

**Issue by Complex682** [Quarris/RebirthOfTheMobs#1]
Not sure if this crashed is cause by configs or something else. Attached is crashlog and configs.
[rotmConfigs.txt](https://github.com/Quarris/RebirthOfTheMobs/files/5212738/rotmConfigs.txt)
[crash-2020-09-12_21.26.13-server.txt](https://github.com/Quarris/RebirthOfTheMobs/files/5212733/crash-2020-09-12_21.26.13-server.txt)

**Comment by SandwichHorror** [comment]
It's possible this is a lovely three-mod cocktail of Fish's Undead rising tamed(?) raven code, Engender specific fireball damage, and ROTM damage detection system. Can you replicate this with other tamed entities (from Fish's or otherwise) and Engender fireballs or damage?

Isn't there some entity conversion damage system in Engender that could be classified strangely?

**Comment by Quarris** [comment]
I couldn't find a cause for this. Seems like Engender is possibly modifying something in vanilla? The only thing that I believe couldve caused this is an entity that is not registered which is weird. I also cannot check the Engenders code since it's closed source.
