### ISSUE TITLE
Vertical speed of some mobs too high when jumping in water

### ISSUE THREAD

**Issue by EliteMeats** [Quarris/RebirthOfTheMobs#4]
Some mobs, I've noticed mostly animals, jump too high when in water.

something about D:globalSwimSpeedMultiplier=1.5

![ezgif-1-5032d24f1fa0](https://user-images.githubusercontent.com/70586468/95772976-9bdef600-0c8b-11eb-837c-14ee0f788021.gif)

**Comment by Quarris** [comment]
The swim speed modifier is an iffy one. I couldn't find a neat solution, since in the code modifying the swim speed attribute changes all 3 directions at the same time. This feature is mostly added with the request of the commissioner and is a known issue, but it's not something that I know how to easily fix. Try using smaller values and hope for the best, or don't use that feature at all. Sorry :/
